### ISSUE TITLE
Running Multisample pipeline

### ISSUE THREAD

**Issue by mcortes-lopez** [OliverVoogd/FLAMES#11]
Hi, 

I am trying to run the multisample pipeline for 3 sc datasets, however I am not sure how to provide the barcodes for each sample separately. I tried it as vectors with the path to each barcode file but that does not seem to work. Can I, otherwise, run the pipeline from the aligned bam files? 
So far I tried this second option by providing a list of bam files, but the problem was that when aligning the fastq files (provided in a list) to the transcriptome, the barcode was lost and consequently no isoform quantification was possible. Do I need perhaps to recreate the fastq files from the bam files after align to the transcriptome? 
I just want to have all these samples, which I already run individually, quantified in the same transcriptome.
Thanks.

**Comment by ChangqingW** [comment]
You could use `find_barcode` function individually on each sample, and then run the pipeline with the demultiplexed reads, setting `match_barcode` to `FALSE`. We will add the support for vector of barcode files soon.
