### ISSUE TITLE
Installation issue on Debian 11

### ISSUE THREAD

**Issue by HaraldWilhelmi** [OliverVoogd/FLAMES#13]
When trying to install the package on Debian 11 with R 4.3 this will fail with errors like this:<pre>
Error: package or namespace load failed for 'FLAMES' in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '.../R/lib/R/library/00LOCK-FLAMES/00new/FLAMES/libs/FLAMES.so':
  .../R/lib/R/library/00LOCK-FLAMES/00new/FLAMES/libs/FLAMES.so: undefined symbol: _ZSt28__throw_bad_array_new_lengthv
</pre>

IMHO this is due to the fact the package (https://bioconductor.org/packages/3.17/bioc/src/contrib/FLAMES_1.6.0.tar.gz)
contains compiled binaries, which are not compatible with the libstdc++6 package of Debian 11 (e.g. ./src/utility/edit_dist.o).
As a workaround we tried that:<pre>
$ wget https://bioconductor.org/packages/3.17/bioc/src/contrib/FLAMES_1.6.0.tar.gz
$ tar xvfz FLAMES_1.6.0.tar.gz
$ cd FLAMES
$ find . -name '*.o' -exec rm {} \;
$ cd ..
$ tar cvfz FLAMES_1.6.0_patched.tgz FLAMES
$ R
> install.packages("FLAMES_1.6.0_patched.tgz", repos=NULL, type="source")
</pre>

That seems to avoid the issue.

**Comment by ChangqingW** [comment]
Thanks for reporting this and sharing your workaround!
