### ISSUE TITLE
Please update vignette

### ISSUE THREAD

**Issue by HenriettaHolze** [OliverVoogd/FLAMES#15]
Hi Oliver,  

I am trying to use FLAMES to demultiplex single cell nanopore data. Installed it today from bioconductor, session info:
`other attached packages:`
`[1] FLAMES_1.2.2`  
I tried using the vignette but the example code throws an error when creating the config file with create_config.  
Could you please update the vignette and recommend default values for the parameters? Thanks! 

Cheers,
Henrietta

**Comment by OliverVoogd** [comment]
Hi Henrietta,
Thanks for using FLAMES.
Would you be able to provide the error that results when using `create_config`? 

Thanks!

**Comment by HenriettaHolze** [comment]
Switched to FLAMES_1.7.4 and it resolved the issue
