### ISSUE TITLE
Error in locating minimap2

### ISSUE THREAD

**Issue by sh0rt2l0ng** [OliverVoogd/FLAMES#20]
I tried to feed blaze2 fastq into flames. But got below error.

Error in if (file_test("-f", file.path(minimap2_dir, "k8")) && file_test("-f",  : 
  missing value where TRUE/FALSE needed
In addition: Warning messages:
1: In base::system2(command = "command", args = c("-v", "minimap2")) :
  error in running command
2: In base::system2(command = "command", args = c("-v", "minimap2")) :
  error in running command
3: In base::system2(command = "command", args = c("-v", "samtools")) :
  error in running command

I tried to evaluate k8 and paftools.js manually. Both are "TRUE". Not sure what caused this.
> file_test("-f", file.path(minimap2_dir, "k8"))
[1] TRUE
> file_test("-f", file.path(minimap2_dir, "paftools.js"))
[1] TRUE

Could you please show some light on this? Thanks!

**Comment by youyupei** [comment]
Hi @sh0rt2l0ng,

Thanks for being interested in FLAMES, to help us better understand the issue, would you be able to share the R code and config file you used?

Thanks

**Comment by sh0rt2l0ng** [comment]
Hi @youyupei ,

Thanks for the reply! Here is the R code and config file generated with the code.

[config_file.json](https://github.com/mritchielab/FLAMES/files/13867715/config_file.json)
[flames_test.txt](https://github.com/mritchielab/FLAMES/files/13867716/flames_test.txt)

**Comment by youyupei** [comment]
Hi @sh0rt2l0ng, 

It seems the `minimap2_dir` was not passed into the `sc_long_pipeline` function. It might be helpful if you add `minimap2_dir=minimap2_dir` when calling `sc_long_pipeline` function.  i.e., 
```
sce <- sc_long_pipeline(annotation = annot, fastq = fastq, genome_fa = genome_fa, minimap2_dir=minimap2_dir,
                          outdir = outdir, config_file = config_file, expect_cell_number = 5000)
```
Also some suggestions: in your config file, you could
1. use more threads by modifying the number (depends on how many cores you have) in `"threads": [1]` to shorten the run time.
2. set ` "bambu_isoform_identification": [true],` for potentially more accurate isoform identification

**Comment by sh0rt2l0ng** [comment]
Hi @youyupei ,

Thanks for your advice. I will definitely try this and let you know the result later. BTW, may I know what's the minimum hardware requirement of FLAMES? I am going to use it for a 150GB fastq.gz from ONT-10X protocol. What's the peak memory usage of each thread in FLAMES? Or which step in FLAMES consumes the most memory in run time.

**Comment by youyupei** [comment]
Hi @sh0rt2l0ng , not sure you still need this information but just in case, from my experience ~150G of fastq file, the peak memory can go to ~60-80G. The steps consume most memory would normally be the mapping step.
