### ISSUE TITLE
quesetion about combinesce

### ISSUE THREAD

**Issue by yuanwsy** [OliverVoogd/FLAMES#24]
Hi,thanks for developing such a useful tools!
When I using the FLAMES-R,I have a question about combine sce:
It seems to combine two short read data with a long read data ,may I use a short read single cell experiment(for example a classical seurat object),with a long read data sce(generating from FLAMES),and do the following analysis?

and another question is that if I want to subset the cell cluster of the longread sce to make a new sce ,what should I do in FLAMES?or in other way,do you have some suggestion?

**Comment by ChangqingW** [comment]
Do you have the same cell barcodes for the long-read and the short-read experiments?

**Comment by yuanwsy** [comment]
yes， they are actually generated from the same single cell library, but some was used to sequencing on illumina platform, some sequencing on ONT platform

**Comment by ChangqingW** [comment]
Perfect! The pipeline was mainly developed to preprocess such data, i.e. demultipexing the long-reads using barcodes identified from the paired short-reads, do alignment, isoform identification & quantification, and create an SCE object for the long-reads.
In regard to your question about combining the two into a single object, we do a function `combine_sce` that does that, but to be honest it is simply putting the two into a `MultiAssayExperiment` object. In addition, it is expecting two short-read libraries: a smaller sub-sample that is paired with the long-read library, and a larger sub-sample. This is to process the data created in [our previous publication](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-021-02525-6). So it might not be directly applicable for your data.
If you already have the SCE objects, maybe combining them with [SingleCellExperiment::altExps](https://rdrr.io/bioc/SingleCellExperiment/man/altExps.html) would be more convenient for downstream analysis.

**Comment by yuanwsy** [comment]
thank you！Another question is that can I use the as.Seurat function in sceasy package to transform the sce object (produced by FLAMES) into a seurat object?

**Comment by ChangqingW** [comment]
I have not used that package before but it will probably work. The SCE object contains the transcript counts (we are still working on incorporating the gene counts) and the transcript annotations (as GRanges), I think you might loose the annotations during the conversion, but you can always refer to the GFF/GTF file from FLAMES' output folder for annotation.
