### ISSUE TITLE
Manually setting threads

### ISSUE THREAD

**Issue by nick-youngblut** [OliverVoogd/FLAMES#28]
It's not clear based on the `FLAMES::create_config` or `FLAMES::sc_long_pipeline` function does on how one manually sets the threads used for BLAZE, minimap2, etc. I'm using FLAMES_1.8.0.

**Comment by ChangqingW** [comment]
This could be done by either `FLAMES::create_config("path/to/out/dir", threads = 1)` or manually editing the file returned by `create_config`.

**Comment by nick-youngblut** [comment]
Thanks! 

I'll could create a PR to update the [`create_config` docs](https://github.com/mritchielab/FLAMES/blob/ababe0648f63fd0365f35cbce6d62ba819ba5d74/R/create_config.R#L13) to include that info, if you'd like.

**Comment by ChangqingW** [comment]
Thanks for offering help, I hope the checks can pass this time.
I will make a new branch for installing devel version on R 4.3
