### ISSUE TITLE
Isoform category quantification

### ISSUE THREAD

**Issue by lscdanson** [OliverVoogd/FLAMES#32]
Hi I'm wondering how I could quantify the isoform structural categories shown in Fig2B in your paper. I could only find three feature metadata slots (i.e. 'transcript_id', 'gene_id', 'FSM_match') in the SCE object generated from the sc_long_pipeline() function and there doesn't seem to be anything relevant. Thanks so much!

**Comment by ChangqingW** [comment]
This was done with SQANTI as per described in the "Isoform classification and splicing analysis" subsection under Methods.

**Comment by lscdanson** [comment]
@ChangqingW thanks for the prompt reply! A further question regarding transcript id to transcript name conversion. It looks like some of the transcript ids are artificially created (e.g. "ENSG00000001629.10_92245974_92294977_1") – are these novel transcripts in the ensembl database? And if there is a way to convert the transcript ids (given some are artificially created) to transcript names (e.g. CD4-201)? Many thanks!

**Comment by ChangqingW** [comment]
The ones with ENSG ids with extra under scores are novel isoforms identified by FLAMES, you won't find the them in public annotation databases because they are novel. I am not sure what you mean by converting to transcript names, they won't have one.

**Comment by lscdanson** [comment]
Thanks for the clarification!
