### ISSUE TITLE
Error starting the FLAMES pipeline

### ISSUE THREAD

**Issue by vasikara17** [OliverVoogd/FLAMES#35]
Hello, thank you for the nice tool!!
I would like to ask you if I am missing something for the starting of the pipeline. I have minimap2 tool in my miniconda folder installed and there is also the K8 but I think that FLAMES cannot find the path. Is there a way to give the absolute path to the function?
Best regards,
Vasiliki 

**10:02:51 AM Wed Jun 12 2024 minimap2_alignError in if (file_test("-f", file.path(minimap2_dir, "k8")) && file_test("-f",  : 

  missing value where TRUE/FALSE needed

In addition: Warning messages:

1: In base::system2(command = "command", args = c("-v", "minimap2")) :

  error in running command

2: In base::system2(command = "command", args = c("-v", "minimap2")) :

  error in running command

3: In base::system2(command = "command", args = c("-v", "samtools")) :

  error in running command**

**Comment by vasikara17** [comment]
Also when I use the minimap2_dir command with the path to minimap2 I get the following error:
**Error in dirname(minimap2_dir) : a character vector argument expected
In addition: Warning message:
In base::system2(command = "command", args = c("-v", "samtools")) :
  error in running command**

**Comment by vasikara17** [comment]
Thank you very much I found out the issue!!

**Comment by rb520826** [comment]
Hi Vasiliki, how did you solve the issue please?
Thanks!

**Comment by vasikara17** [comment]
Hello, I actually solve it partially! 
the minimap2 path is now ok however I have the same error coming after with samtools! 
Best,
Vasiliki

**In base::system2(command = "command", args = c("-v", "samtools")) :
error in running command****

**Comment by ChangqingW** [comment]
I added the `minimap2` and `k8` arguments to `sc_long_pipeline` the user can provide the paths to them if it is not available in `$PATH`.
Should probably do it for samtools as well -- I thought I had it use Rsamtools when samtools is not available, apparently that did not work.

**Comment by vasikara17** [comment]
Hello, 
I have still the samtools error. I have tried to give the path for samtools like for minimap2 but it did not work. 
Is there any temporary solution to this?

Thanks in advance!

**Comment by vasikara17** [comment]
Hello, any updates on the issue?

**Comment by ChangqingW** [comment]
I'll add another argument for samtools path. You should be able to get around this by adding samtools to your $PATH environment variable though

**Comment by ChangqingW** [comment]
Let me know if it still errors after https://github.com/mritchielab/FLAMES/commit/d4727af4138ccc014d0a13f5b9ea91d1083016db
