### ISSUE TITLE
Visualizations

### ISSUE THREAD

**Issue by vasikara17** [OliverVoogd/FLAMES#36]
Hello, 
do the visualizations work also for the bulk_long_pipeline?
It is not so clear in the vignette.

Best,
Vasiliki

**Comment by ChangqingW** [comment]
No I don't think so, we will update the docs

**Comment by vasikara17** [comment]
So, the tool takes only single cell data? And something else if you give demultiplexed fastq files from scRNAseq does it need also to have the barcodes available? I am using another technology not 10x so I am not sure.

**Comment by ChangqingW** [comment]
Yes it will have to be single-cell data. Yes the demultipexed fastq should have the barcode in the identifier field like so:
`@TCTGGCTCATTCTCCG_GCAGCGAAGCCC#32b5d571-ad88-4ac7-bc46-f2ff03de65aa` i.e. `@BC_UMI#otherstuff`
