### ISSUE TITLE
please fix DESCRIPTION 

### ISSUE THREAD

**Issue by vjcitn** [OliverVoogd/FLAMES#5]
> read.dcf("DESCRIPTION")
Error in read.dcf("DESCRIPTION") : 
  Line starting 'long read RNA-seq da ...' is malformed!

See https://cran.r-project.org/doc/manuals/r-release/R-exts.html#The-DESCRIPTION-file

**Comment by OliverVoogd** [comment]
Added tab on second line of long Description
